[[api-design-review-process]]
= API Design Review Process

== Why
We believe in APIs. We are just at the beginning of our journey to an API driven company. 
There is no clear roadmap how to reach our goal. For sure it will be ways in which we stumble, 
sometimes fail but hopefully succeed in the end.

There will be pros and cons how to handle and apply the style guide to real projects. 
There are many things to learn and to share with another. We have to keep improving the style guide,
review process, and tools to capture our evolving knowledge and experience.

To formalize the learning process we decided to establish the API Design Review Process.
Each new or refactored API SHOULD be reviewed through this process.

== Feedback
We have now done a couple of API design reviews. Please give us feedback how we can improve this process!

[#10001]
== {SHOULD} API Design Review Process

*Who is responsible for scheduling the review?*
A representative of the project team that creates the service MUST contact the Architecture team. 
In most cases the representative is the API designer/architect.

*How to plan the review?*
It is the responsibility of the team to plan their resources for the API review and to talk
with the team leaders of Functional and Data Architecture to organize reviewers. 
Together they decide on the appropriate time box for the review.

*Tooling*
Currently we are experimenting https://www.apicur.io/[APICURIO] for API review.

*API description*
It is necessary to provide a formal description of the API to review it. 
The API designer has to provide an OPENAPI (or Swagger) description or an equivalent description. 
Providing a running system or a mock to work with the API is highly appreciated.

*Reviewing the API*
It is up to the API designer and reviewer how to perform the review. It is a good idea to schedule a meeting
and step through the API and talk with the reviewers about the functionality and intention.
That's a good way to cut down review times because questions and missunderstandings can be solved immediately.
Others prefer to review the API without a formal meeting.

---
This chapter was adopted from the https://github.com/Haufe-Lexware/api-style-guide/blob/master/api-design-review-process/api-design-review-process.md[Haufe-Lexware/api-style-guide]
