[[appendix-changelog]]
[appendix]
= Changelog

This change log only contains major changes compared with Zalando Guidelines [Last updated 2020-03-19 06:48:12 UTC].

Non-major changes are editorial-only changes or minor changes of existing guidelines, e.g. adding new error code.
Major changes are changes that come with additional obligations, or even change an existing guideline obligation.
The latter changes are additionally labeled with "Rule Change" here.

To see a list of all changes, please have a look at the https://github.com/f-fabre/sismage-apollo-restful-api-guidelines/commits/master[commit list in Github].

[[rule-changes]]
== Rule Changes

* `2020-04-07:` Removed chapters "Proprietary Headers" and "Events"
* `2020-04-07:` Added rule {MUST} not use URI versioning within OpenAPI Specification <<1003,[1003]>>
* `2020-04-07:` Added rule  {MUST} use URI versioning at deployment level ONLY <<1002,[1002]>>
* `2020-04-06:` Added chapter "Key principles"
* `2020-04-05:` Introduced the changelog. From now on all rule changes on API guidelines will be recorded here.
* `2019-01-24:` From Zalando Guidelines - https://opensource.zalando.com/restful-api-guidelines/#appendix-changelog
