[[key-principles]]
= Key principles

We are just at the beginning of our journey to an API driven company.
We highlighted *Key principles* as a starting point for on-boarded teams, 
but we *strongly encourage* our teams to *carefully read the entire document*. 

The purpose of our "RESTful API guidelines" is to define standards to successfully 
establish "consistent API look and feel" quality.
*Ideally, all SISMAGE & Apollo APIs will look like the same author created them.*

[cols="22%,78%,frame="topbot",options="header"]
|=========================================================
| *Topic* | *Key principles*
| *General guidelines* | 
{MUST} follow API first principle <<100,[100]>>

{SHOULD} provide API user <<101,[101]>>

{MUST} write APIs using U.S. English <<103,[103]>>
| *API Design Review Process* |
{SHOULD} API Design Review Process <<1001,[1001]>>
| *Meta information*    |
{MUST} contain API meta information <<218,[218]>>

{MUST} use semantic versioning <<116,[116]>>
| *Compatibility*    |
{MUST} always return JSON objects as top-level data structures <<110,[110]>>

{MUST} use URI versioning at deployment level *ONLY* <<1002,[1002]>>

{MUST} not use URI versioning within OpenAPI Specification <<1003,[1003]>>
| *JSON Guidelines*    |
{MUST} property names must be ASCII snake_case (and never camelCase): `^[a-z_][a-z_0-9]*$` <<118,[118]>>

{MUST} declare enum values using UPPER_SNAKE_CASE format <<240,[240]>>

{SHOULD} pluralize array names <<120,[120]>>

{MUST} not use null for boolean properties <<122,[122]>>

{SHOULD} not use null for empty arrays <<124,[124]>>

{SHOULD} represent enumerations as strings <<125,[125]>>

{SHOULD} define dates properties compliant with RFC 3339 <<126,[126]>>

{SHOULD} define time durations and intervals properties conform to ISO 8601 <<127,[127]>>
| *Data formats*    |
{MUST} use JSON to encode structured data <<167,[167]>>

{MUST} use standard date and time formats <<169,[169]>>

{SHOULD} use standards for country, language and currency codes <<170,[170]>>

{MUST} define format for number and integer types <<171,[171]>>
| *API naming*    |
{MUST} use lowercase separate words with hyphens for path segments <<129,[129]>>

{MUST} use snake_case (never camelCase) for query parameters <<130,[130]>>

{MUST} pluralize resource names <<134,[134]>>

{SHOULD} not use /api as base path <<135,[135]>>

{MUST} avoid trailing slashes <<136,[136]>>
| *Resources*    |
{MUST} avoid actions — think about resources <<138,[138]>>
 
{MUST} keep URLs verb-free <<141,[141]>>
 
{MUST} identify resources and sub-resources via path segments <<143,[143]>>
| *HTTP requests*    | 
{MUST} use HTTP methods correctly <<148,[148]>>
| *HTTP status codes and errors*    | 
{MUST} specify success and error responses <<151,[151]>>
 
{MUST} use standard HTTP status codes <<150,[150]>>
 
{SHOULD} not expose stack traces <<177,[177]>>
| *Hypermedia*    |
{MUST} use REST maturity level 2 <<162,[162]>>

{MUST} use full, absolute URI <<217,[217]>>
|*Common headers* |
{MUST} use `Content-*` headers correctly <<178,[178]>>
|*API Operation* |
{MUST} publish Open API specification <<192,[192]>>
|=========================================================
